### PR TITLE
added travis.yml

### PR DESCRIPTION
**Pull request by stenoritama**
- I think the code in pull request should be tested before merging and want to use travis-CI. (testing open source project is free.)
- I added travis.yml. After merging this, pull request will be trigger for running test on CI.

### CODE REVIEW

**Comment by stenoritama** [comment]
@piroyoung hey!

**Comment by stenoritama** [comment]
It seems that the build speed becomes faster by using `sudo: false`.
For more, see
https://blog.travis-ci.com/2014-12-17-faster-builds-with-container-based-infrastructure/

**Comment by piroyoung** [comment]
lgtm!

**Comment by piroyoung** [comment]
I'll merge it!

**Comment by stenoritama** [comment]
@piroyoung thanks!!

**Pull request merged**
